# Generated by Django 6.1.1 on 2026-09-07 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_doctor', '0002_analysishistory_dataset_delete_uploadeddataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_column', models.CharField(max_length=255)),
                ('problem_type', models.CharField(max_length=50)),
                ('best_model', models.CharField(max_length=255)),
                ('model_results', models.JSONField()),
                ('feature_importance', models.JSONField(default=list)),
                ('model_file', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='data_doctor.dataset')),
            ],
        ),
    ]
